### ISSUE TITLE
Binding { type: 'once', ... } fires Query.off which returns an error

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#36]
Hi there!

I get an error after binding the data once, like this:

```js
@firebaseConnect((props) => ([
  { type: 'once', path: DH.getUserProfile(props.uid) },
  { type: 'once', path: DH.getUserGoalsPath(props.uid) },
]))
```

Below is the error I get:

```js
database.js:130 Uncaught Error: Query.off failed: first argument must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".
    at jf (http://localhost:8080/index.js:37664:156)
    at U.g.Ic (http://localhost:8080/index.js:37707:59)
    at unsetWatcher (http://localhost:8080/index.js:36456:46)
    at unWatchEvent (http://localhost:8080/index.js:34494:35)
    at http://localhost:8080/index.js:34516:13
    at Array.forEach (native)
    at unWatchEvents (http://localhost:8080/index.js:34515:18)
    at FirebaseConnect.componentWillUnmount (http://localhost:8080/index.js:31687:37)
    at http://localhost:8080/index.js:23652:26
    at measureLifeCyclePerf (http://localhost:8080/index.js:23318:13)
```

I figure this is because 'once' does not have any watchers which should be unset. However, couldn't find a fix in the code. Would appreciate your help on this one!

**Comment by prescottprue** [comment]
Just to confirm I get the reproduction of the problem right, which version are you using?

**Comment by DeividasK** [comment]
v1.1.5

**Comment by prescottprue** [comment]
Try [`v1.2.0-rc.2`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.2.0-rc.2) and see if it fixes it for you. It skips calling off for `once`

**Comment by DeividasK** [comment]
Fix works.

**Comment by prescottprue** [comment]
Great to hear! Planning on releasing `v1.2.0` in a few minutes (which will include this fix).
