### ISSUE TITLE
mapState is not a function

### ISSUE THREAD

**Issue by beckmeindia** [prescottprue/react-redux-firebase#46]
Hey, 
I have been getting this error while running this library. Is this particularly due to integrating react-redux with react-redux-firebase or some other error.

I'm using:  "react-redux": "^4.0.0",  "react-redux-firebase": "^1.2.0-beta"

[1] [piping] can't execute file: C:\Users\gemini\Desktop\react-universal\bin\server.js
[1] [piping] error given was: TypeError: mapState is not a function
[1]     at Connect.configureFinalMapState (C:\Users\gemini\Desktop\react-universal\node_modules\react-redux\lib\components\connect.js:155:27)
[1]     at Connect.computeStateProps (C:\Users\gemini\Desktop\react-universal\node_modules\react-redux\lib\components\connect.js:142:23)
[1]     at Connect.updateStatePropsIfNeeded (C:\Users\gemini\Desktop\react-universal\node_modules\react-redux\lib\components\connect.js:204:35)
[1]     at Connect.render (C:\Users\gemini\Desktop\react-universal\node_modules\react-redux\lib\components\connect.js:340:40)
[1]     at C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\ReactCompositeComponent.js:796:21
[1]     at measureLifeCyclePerf (C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
[1]     at null.ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext (C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\React
CompositeComponent.js:795:25)
[1]     at null.ReactCompositeComponent._renderValidatedComponent (C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\ReactCompositeComponent.js:822:32)
[1]     at null.ReactCompositeComponent.performInitialMount (C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\ReactCompositeComponent.js:362:3
0)
[1]     at null.ReactCompositeComponent.mountComponent (C:\Users\gemini\Desktop\react-universal\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)

Please suggest how to resolve it.

Thanks

**Comment by prescottprue** [comment]
This is not enough information to determine whether it is related to your usage of `react-redux-firebase` or not.

Could you possibly send a link to a repo to reproduce this problem? If you don't want to share publicly, I am also available on  [gitter](https://gitter.im/redux-firebase/Lobby).

Side Note:
The current version is `v1.2.2`. I don't believe it will fix anything for you, but it is worth a try.

**Comment by beckmeindia** [comment]
Hey, 
    After changing the version and updating the packages, this is the new error
 
[1] [piping] error given was: Error: Invalid value of type object for mapStateTo
Props argument when connecting component App.
[1]     at C:\Users\gemini\Desktop\react-universal\node_modules\react-redux\lib\
connect\connect.js:61:11


I shall email you the code repo if that is fine to check

**Comment by beckmeindia** [comment]
It was a problem with the repository that i am using. So it works now.

Thanks!
