### ISSUE TITLE
./factoryWithThrowingShims could not be found

### ISSUE THREAD

**Issue by UbaidAhmedAwan** [prescottprue/react-redux-firebase#505]
error: bundling failed: Error: Unable to resolve module ./factoryWithThrowingShims from /Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/index.development.js: The module ./factoryWithThrowingShims could not be found from /Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/index.development.js. Indeed, none of these files exist:

/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/factoryWithThrowingShims(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)
/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/react-advanced-form/lib/factoryWithThrowingShims/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)
at ModuleResolver.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
at ResolutionRequest.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
at DependencyGraph.resolveDependency (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
at Object.resolve (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/lib/transformHelpers.js:116:25)
at dependencies.map.result (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
at Array.map ()
at resolveDependencies (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
at /Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
at Generator.next ()
at step (/Users/ubaidahmedawan/Desktop/Tabedaar/tabedaar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)

**Comment by prescottprue** [comment]
@UbaidAhemdAwan It looks like this might be due to transpilation issues and also looks to point to `react-advanced-form` instead of `react-redux-firebase`.

Is there any way you can provide more in the way of setup logic, package file, and babel/webpack settings?

**Comment by prescottprue** [comment]
Closing since no repro provided.
