### ISSUE TITLE
Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by andreyluiz** [prescottprue/react-redux-firebase#67]
I have configured my entire environment correctly, as I can see, but I got this error:

```
TypeError: Cannot read property 'ref' of undefined
   at FirebaseConnect.componentWillMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-redux-firebase/lib/connect.js:87:29)
   at /home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:348:23
   at measureLifeCyclePerf (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:347:9)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
```

Follow my configuration:

**configureStore.js**
```javascript
const config = {
    apiKey: '[...]',
    authDomain: '[...]',
    databaseURL: '[...]',
    storageBucket: '[...]',
};

// eslint-disable-next-line no-underscore-dangle
const composeEnhancers = (window && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose;
const store = createStore(reducers, persistedState, composeEnhancers(
    applyMiddleware(thunk),
    reactReduxFirebase(config),
));
```

**reducers.js**
```javascript
import { combineReducers } from 'redux';
import { firebaseStateReducer } from 'react-redux-firebase';
import users from './users';

export default combineReducers({
  users,
  firebase: firebaseStateReducer,
});
```

**AdminUserListPage.js**
```javascript
import { firebaseConnect, helpers } from 'react-redux-firebase';
import UserAppContainer from './UserAppContainer';
import AdminUserList from './AdminUserList';

const { dataToJS } = helpers;

const mapStateToProps = ({ firebase }) => ({
  users: dataToJS(firebase, '/Users'),
});

@firebaseConnect({ path: '/Users' })
@connect(mapStateToProps)
export default class AdminUserListPage extends Component { // eslint-disable-line
  render() {
    return (
      <UserAppContainer admin>
        <AdminUserList {...this.props} />
      </UserAppContainer>
    );
  }
}
```

**AdminUserList.js**
```javascript
import { helpers } from 'react-redux-firebase';

const { isLoaded, isEmpty } = helpers;

type Props = {
  users: Object,
};

export default class AdminUserList extends Component {
  props: Props

  render() {
    const { users } = this.props;
    return (
      <div data-root id="admin-user-list">
        <h1>Usuários</h1>
        {!isLoaded(users) && <p className="loading">Carregando usuários...</p>}
        {isEmpty(users) && <p className="empty">Não há usuários cadastrados.</p>}
        {users.map(user => { ... })}
      </div>
    );
  }
}
```

> AdminUserListPage is the wrapper of AdminUserList. I omitted some imports for brevity.

Any idea what is this about?

**Comment by prescottprue** [comment]
Firebase connect accepts an array [as detailed in the docs](http://react-redux-firebase.com/docs/api/connect.html). You have provided an object.

Try:
```js
@firebaseConnect([ { path: '/Users' } ]) // an array instead of a single object
// or with the string notation:
@firebaseConnect([ '/Users' ]) // string notation
```

**Comment by andreyluiz** [comment]
Well, this was indeed wrong, but my error is before that. Actually I have SSR in my application.

So I have two stores: the one in the server, and another in the client. I configured the lib only for the client store. Since my route renders in the server, the ref to firebase does not exist.

I tried to register the middleware in redux's store in server side, however, and error regarding the environment prompts in:

```
Error: This operation is not supported in the environment this application is running on. "location.protocol
" must be http or https and web storage must be enabled.
```

Obviously this can't be used server side. But, how can I use the library with SSR? Below is my full `configureStore.js` implementation:

```javascript
import { compose, createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import throttle from 'lodash/throttle';
import { reactReduxFirebase } from 'react-redux-firebase';
import reducers from './reducers';
import { loadState, saveState } from './localStorage';

export default (initialState = {}, server = false, test = false) => {
  const config = {
    apiKey: '[...]',
    authDomain: '[...]',
    databaseURL: '[...]',
    storageBucket: '[...]',
  };

  if (server) {
    return createStore(reducers, compose(
      applyMiddleware(thunk),
      reactReduxFirebase(config),
    ));
  }

  const persistedState = test ? initialState : Object.assign({}, initialState, loadState());

  // eslint-disable-next-line no-underscore-dangle
  const composeEnhancers = (window && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose;
  const store = createStore(reducers, persistedState, composeEnhancers(
      applyMiddleware(thunk),
      reactReduxFirebase(config),
  ));

  if (!test) {
    store.subscribe(throttle(() => {
      const { user } = store.getState();
      saveState({
        user,
      });
    }, 1000));
  }

  return store;
};
```

**Comment by prescottprue** [comment]
This is due to the fact that Firebase's redirect capabilities do not work outside of an http/https environment (because it is running on Node). There is a setting called `enableRedirectHandling`, which is [listed within the docs](http://react-redux-firebase.com/docs/api/compose.html), that allows disabling.

**NOTE**: Login through redirect will most not work after you apply this config. This is intended, and will remain this way until Firebase supports this functionality outside of http/https environments.

Include this in your config:
```js
{
  enableRedirectHandling: false
}
```

**Comment by andreyluiz** [comment]
Thank you @prescottprue.
